s = input("Digite algo: ")
print('O tipo primitivo desse valor é: {}'.format(type(s)))
print(f'Só tem espaços? {s.isspace()}')
print(f'É numérico? {s.isnumeric()}')
print(f'É alfabético? {s.isalpha()}')
print(f'É ascii? {s.isascii()}')
print(f'É decimal? {s.isdecimal()}')
print(f'É escrito em letras maiúsculas? {s.isupper()}')
print(f'É escrito em letras minúsculas? {s.islower()}')
print(f'Está capitalizado? {s.istitle()}')